"""
Canonical country name mappings for normalizing INDEC and Comtrade data.
Both sources map to the same canonical Spanish names.
"""

# INDEC name -> canonical name
# Only entries where the name differs from canonical
INDEC_TO_CANONICAL = {
    "República Federal de Alemania": "Alemania",
    "Viet Nam": "Vietnam",
    "Corea (Sur), Rep. de": "Corea del Sur",
    "Corea (Norte), Rep. Popular Democrática de": "Corea del Norte",
    "Rusia Federación de": "Rusia",
    "Hong Kong (China)": "Hong Kong",
    "República Checa": "Chequia",
    "República Dominicana": "Rep. Dominicana",
    "Nueva Zelandia": "Nueva Zelanda",
    "Emiratos Árabes Unidos": "Emiratos Árabes",
    "Côte d'Ivoire (Costa de Marfil)": "Costa de Marfil",
    "Bahrein": "Baréin",
    "Belarús": "Bielorrusia",
    "Bosnia y Herzegovina": "Bosnia Herzegovina",
    "Congo, Rep. Democrática del": "Rep. Dem. del Congo",
    "Congo, Rep. del": "Congo",
    "Guinea Ecuatorial": "Guinea Ecuatorial",
    "Kazajstán": "Kazajistán",
    "Kenya": "Kenia",
    "Macao (China)": "Macao",
    "Macedonia (ex República Yugoslava de)": "Macedonia del Norte",
    "Moldavia, República de": "Moldavia",
    "República Centroafricana": "Rep. Centroafricana",
    "Taiwán": "Taiwán",
    "Turkmenistán": "Turkmenistán",
    # INDEC special zones → merge into parent country
    "Colonia (Uruguay)": "Uruguay",
    "Florida (Uruguay)": "Uruguay",
    "Nueva Helvecia - Colonia Suiza  (Uruguay)": "Uruguay",
    "Nueva Palmira (Uruguay)": "Uruguay",
    "Punta Pereira (Uruguay)": "Uruguay",
    "ZF LIBERTAD (URUGUAY)": "Uruguay",
    "ZF UPM FRAY BENTOS (EX RIO NEGRO) (URUGUAY)": "Uruguay",
    "Zonamerica (ex Montevideo) (Uruguay)": "Uruguay",
    "Manaos (Brasil)": "Brasil",
    "Colón (Panamá)": "Panamá",
    "Punta Arenas (Chile)": "Chile",
    "Puerto Rico": "Puerto Rico",
    "Zona Franca Coyol Alajuela(Costa Rica)": "Costa Rica",
    # Skip these
    "Confidencial": None,
    "Indeterminado (continente)": None,
    "Indeterminado (Europa)": None,
    "Exportaciones e Importaciones Simplificadas": None,
    "Teritorios vinculados a Francia(Australia)": None,
    "Territorios Vinculados a España(África)": None,
    "Territorios Vinculados a Francia(África)": None,
    "Territorios vinculados a Estados Unidos  (América)": None,
    "Territorios vinculados al Reino Unido de Gran Bretaña e Irlanda del No (América)": None,
    "Territorios vinculados al Reino Unido de Gran Bretaña e Irlanda del No(Europa)": None,
    "Antillas Holandesas (territorio vinculado a Países Bajos)": "Países Bajos",
    "Bonaire, San Eustatius y Saba": "Países Bajos",
}

# Comtrade English name -> canonical Spanish name
# Only entries where translation is needed (names already in Spanish pass through)
COMTRADE_TO_CANONICAL = {
    "Brazil": "Brasil",
    "United States of America": "Estados Unidos",
    "USA": "Estados Unidos",
    "China, Hong Kong SAR": "Hong Kong",
    "Germany": "Alemania",
    "United Kingdom": "Reino Unido",
    "France": "Francia",
    "Italy": "Italia",
    "Spain": "España",
    "Netherlands": "Países Bajos",
    "Belgium": "Bélgica",
    "Japan": "Japón",
    "Rep. of Korea": "Corea del Sur",
    "Mexico": "México",
    "Canada": "Canadá",
    "Russian Federation": "Rusia",
    "Turkey": "Turquía",
    "Türkiye": "Turquía",
    "Saudi Arabia": "Arabia Saudita",
    "United Arab Emirates": "Emiratos Árabes",
    "South Africa": "Sudáfrica",
    "Thailand": "Tailandia",
    "Viet Nam": "Vietnam",
    "Malaysia": "Malasia",
    "Philippines": "Filipinas",
    "Singapore": "Singapur",
    "Switzerland": "Suiza",
    "Sweden": "Suecia",
    "Norway": "Noruega",
    "Denmark": "Dinamarca",
    "Finland": "Finlandia",
    "Poland": "Polonia",
    "Ireland": "Irlanda",
    "Greece": "Grecia",
    "Czechia": "Chequia",
    "Czech Republic": "Chequia",
    "Romania": "Rumania",
    "Hungary": "Hungría",
    "Egypt": "Egipto",
    "Algeria": "Argelia",
    "Morocco": "Marruecos",
    "Tunisia": "Túnez",
    "Kenya": "Kenia",
    "Ethiopia": "Etiopía",
    "Peru": "Perú",
    "Venezuela": "Venezuela",
    "Bolivia (Plurinational State of)": "Bolivia",
    "Dominican Rep.": "Rep. Dominicana",
    "Panama": "Panamá",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "New Zealand": "Nueva Zelanda",
    "Pakistan": "Pakistán",
    "Iran": "Irán",
    "Iraq": "Irak",
    "Oman": "Omán",
    "Bahrain": "Baréin",
    "Jordan": "Jordania",
    "Lebanon": "Líbano",
    "Ukraine": "Ucrania",
    "Belarus": "Bielorrusia",
    "Kazakhstan": "Kazajistán",
    "Uzbekistan": "Uzbekistán",
    "Croatia": "Croacia",
    "Serbia": "Serbia",
    "Bulgaria": "Bulgaria",
    "Slovakia": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Lithuania": "Lituania",
    "Latvia": "Letonia",
    "Estonia": "Estonia",
    "Luxembourg": "Luxemburgo",
    "Cyprus": "Chipre",
    "Iceland": "Islandia",
    "China, Taiwan Province of": "Taiwán",
    "Taiwan": "Taiwán",
    "Dem. Rep. of the Congo": "Rep. Dem. del Congo",
    "Bosnia Herzegovina": "Bosnia Herzegovina",
    "North Macedonia": "Macedonia del Norte",
    "Rep. of Moldova": "Moldavia",
    "United Rep. of Tanzania": "Tanzania",
    "Syria": "Siria",
    "Libya": "Libia",
    "State of Palestine": "Estado de Palestina",
    "Afghanistan": "Afganistán",
    "Antigua and Barbuda": "Antigua y Barbuda",
    "Azerbaijan": "Azerbaiyán",
    "Belize": "Belice",
    "Cambodia": "Camboya",
    "Cameroon": "Camerún",
    "Comoros": "Comoras",
    "Congo": "Congo",
    "Côte d'Ivoire": "Costa de Marfil",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Gabon": "Gabón",
    "Haiti": "Haití",
    "Mauritius": "Mauricio",
    "Niger": "Níger",
    "Sierra Leone": "Sierra Leona",
    "Turkmenistan": "Turkmenistán",
    "Curaçao": "Curazao",
    "China, Macao SAR": "Macao",
    # Skip aggregates
    "Other Asia, nes": None,
    "Areas, nes": None,
    "World": None,
    "Bunkers": None,
    "Free Zones": None,
    "Special Categories": None,
    "Unspecified": None,
}


def normalize_indec_name(name):
    """Normalize an INDEC country name to canonical Spanish."""
    if name in INDEC_TO_CANONICAL:
        return INDEC_TO_CANONICAL[name]
    return name


def normalize_comtrade_name(name):
    """Normalize a Comtrade country name to canonical Spanish."""
    if name in COMTRADE_TO_CANONICAL:
        return COMTRADE_TO_CANONICAL[name]
    return name
